import os
from celery import Celery
import base64
import io

from modules.db_manager import SessionLocal
from modules.models import DataSource
from modules.data_loader import sync_single_source
from modules.llm_manager import ask_llm
from modules.s3_storage import s3_client
from modules.settings import CHARTS_FOLDER
from modules.models import Page, Chart, DataSource
from modules.io_manager import BundleManager

REDIS_URL = os.getenv("REDIS_URL", "redis://redis:6379/0")

# Инициализируем Celery
celery_app = Celery('genai_dashboard', broker=REDIS_URL)
celery_app.conf.result_backend = REDIS_URL

@celery_app.task(name="update_source_task", bind=True)
def update_source_task(self, source_id: int, injected_creds: dict = None):
    """Фоновая задача для обновления одного источника данных"""
    db = SessionLocal()
    try:
        # 1. Достаем источник из БД по его ID
        src = db.query(DataSource).get(source_id)
        if not src:
            return {"status": False, "msg": f"Источник {source_id} не найден", "filename": "Unknown"}

        # 2. Собираем конфиг, как того ожидает функция sync_single_source
        # Достаем техническое имя файла скрипта (например, ws_1_script.py), если обработчик привязан
        handler_file = src.handler.technical_name if src.handler else None
        
        task_dict = {
            "connector_id": src.connector_id,
            "filename": src.filename,
            "config": src.config_json or {},
            "handler": handler_file
        }
        
        # Пробрасываем креды от Google (если они есть)
        if injected_creds:
            task_dict["config"]["_injected_creds"] = injected_creds

        # 3. Запускаем тяжелый процесс!
        ok, msg, _ = sync_single_source(task_dict)
        
        # Возвращаем результат в Streamlit
        return {"status": ok, "msg": msg, "filename": src.filename}
        
    except Exception as e:
        return {"status": False, "msg": str(e), "filename": "Unknown"}
    finally:
        db.close()


def clean_gemini_code(text):
    """Очищает ответ AI от маркдаун-тегов"""
    if "```python" in text:
        text = text.split("```python")[1]
        if "```" in text: text = text.split("```")[0]
    elif "```" in text:
        text = text.split("```")[1]
        if "```" in text: text = text.split("```")[0]
    return text.strip()

@celery_app.task(name="generate_chart_task", bind=True)
def generate_chart_task(self, prompt, py_name, display_title, sel_prov, sel_model, active_ws_id, current_page_name, ds_ids, user_id):
    """Фоновая задача для генерации кода графика через AI"""
    db = SessionLocal()
    try:
        system_msg = (
            "Ты Senior Python Developer. Верни ТОЛЬКО валидный Python код всего модуля. Без маркдауна.\n"
            "🚨 КРИТИЧЕСКОЕ ПРАВИЛО: НИКОГДА не используй st.sidebar. Все виджеты (selectbox, slider) пиши внутри функции render.\n"
            "ВАЖНО ПО PLOTLY 5.X:\n"
            "1. НИКОГДА не используй устаревшие параметры: 'titlefont', 'tickfont'.\n"
            "2. Правильный синтаксис шрифтов: dict(title=dict(text='Name', font=dict(size=14))).\n"
            "3. Вместо 'margin' в layout используй update_layout(margin=dict(l=..., r=...))."
        )
        # 1. Запрашиваем код у нейросети
        success, result_text = ask_llm(sel_prov, sel_model, system_msg, prompt, user_id=user_id)
        
        if not success:
            return {"status": False, "msg": f"Сбой API: {result_text}"}
            
        # 2. Сохраняем код в файл и S3
        code_text = clean_gemini_code(result_text)
        safe_prompt = prompt.replace('"""', "'''")
        file_content = f'"""\n--- GENERATED BY {sel_prov} ({sel_model}) ---\nPROMPT:\n{safe_prompt}\n"""\n\n{code_text}'
        
        path = os.path.join(CHARTS_FOLDER, py_name)
        with open(path, "w", encoding="utf-8") as f:
            f.write(file_content)
        s3_client.put_text("charts", py_name, file_content)
        
        # 3. Регистрируем график в БД
        new_chart = Chart(workspace_id=active_ws_id, technical_name=py_name, display_name=display_title)
        db.add(new_chart)
        
        # Привязываем источники данных
        sources = db.query(DataSource).filter(DataSource.id.in_(ds_ids)).all()
        new_chart.data_sources.extend(sources)
        
        # Привязываем к текущей странице
        page = db.query(Page).filter(Page.workspace_id == active_ws_id, Page.name == current_page_name).first()
        if not page:
            page = db.query(Page).filter(Page.workspace_id == active_ws_id).first()
        if page:
            page.charts.append(new_chart)
            
        db.commit()
        return {"status": True, "msg": "Готово"}
        
    except Exception as e:
        db.rollback()
        return {"status": False, "msg": str(e)}
    finally:
        db.close()


@celery_app.task(name="edit_chart_task", bind=True)
def edit_chart_task(self, prompt, sys_msg, fname, sel_prov, sel_model, user_id):
    """Фоновая задача для редактирования существующего графика через AI"""
    try:
        # 1. Запрашиваем код у нейросети
        success, result_text = ask_llm(sel_prov, sel_model, sys_msg, prompt, user_id=user_id)
        
        if not success:
            return {"status": False, "msg": f"Сбой API: {result_text}"}
            
        # 2. Очищаем код (используем уже существующую функцию clean_gemini_code)
        n_code = clean_gemini_code(result_text)
        
        # 3. Сохраняем измененный код локально и в S3
        path = os.path.join(CHARTS_FOLDER, fname)
        with open(path, "w", encoding="utf-8") as f:
            f.write(n_code.strip())
        s3_client.put_text("charts", fname, n_code.strip())
        
        return {"status": True, "msg": "Готово"}
        
    except Exception as e:
        return {"status": False, "msg": str(e)}


@celery_app.task(name="analyze_chart_task", bind=True)
def analyze_chart_task(self, chart_id, code, data_sample_str, user_id, sel_prov, sel_model, user_prompt="", fig_snapshot=""):
    """Фоновая задача для генерации аналитического комментария к графику"""
    try:
        system_msg = (
            "Ты профессиональный бизнес-аналитик и эксперт по данным. "
            "Твоя задача: изучить код графика, предоставленный образец сырых данных, "
            "а также текущие отфильтрованные данные (снапшот), которые пользователь видит на экране прямо сейчас. "
            "Выдай краткий, но глубокий инсайт. Найди тренды, аномалии или дай совет по бизнесу. "
            "Пиши на русском языке, используй Markdown. Будь лаконичен."
        )
        
        # Базовая часть промпта
        prompt = (
            f"### КОД ГРАФИКА:\n```python\n{code}\n```\n\n"
            f"### ОБРАЗЕЦ СЫРЫХ ДАННЫХ (CSV):\n```csv\n{data_sample_str}\n```\n\n"
        )
        
        # 1. Если удалось снять "снапшот" с графика — добавляем его
        if fig_snapshot and fig_snapshot != "Данные снапшота отсутствуют" and "Сложный график" not in fig_snapshot:
            prompt += (
                f"### ТЕКУЩИЕ ДАННЫЕ НА ЭКРАНЕ (СНАПШОТ):\n"
                f"Внимание: это точные значения (X и Y), которые остались после применения фильтров на графике:\n"
                f"{fig_snapshot}\n\n"
            )
            
        # 2. Если пользователь ввел свои пожелания — фокусируем ИИ на них
        if user_prompt:
            prompt += (
                f"### ОСОБЫЕ ПОЖЕЛАНИЯ ОТ ПОЛЬЗОВАТЕЛЯ:\n"
                f"«{user_prompt}»\n\n"
                "СТРОГО следуй этим инструкциям при анализе. Сделай акцент на том, о чем просит пользователь."
            )
        else:
            # Дефолтная задача, если пользователь ничего не написал
            prompt += "Проанализируй эти данные и дай 3-4 ключевых инсайта."

        # Отправляем запрос в ИИ
        success, result_text = ask_llm(sel_prov, sel_model, system_msg, prompt, user_id=user_id)
        
        if success:
            return {"status": True, "msg": result_text, "chart_id": chart_id}
        else:
            return {"status": False, "msg": f"Ошибка AI: {result_text}"}
            
    except Exception as e:
        return {"status": False, "msg": str(e)}




@celery_app.task(name="import_bundle_task", bind=True)
def import_bundle_task(self, b64_data, workspace_id, target_page):
    """Фоновая задача для импорта .geb архивов"""
    try:
        # Декодируем Base64 обратно в бинарный файл
        file_bytes = base64.b64decode(b64_data)
        file_io = io.BytesIO(file_bytes)
        
        # Запускаем нашу исправленную функцию
        success, msg = BundleManager.import_bundle(file_io, workspace_id, target_page)
        
        if success:
            return {"status": True, "msg": f"Импорт завершен"}
        else:
            return {"status": False, "msg": msg}
            
    except Exception as e:
        return {"status": False, "msg": str(e)}



@celery_app.task(name="chat_llm_task", bind=True)
def chat_llm_task(self, sel_prov, sel_model, history_context, user_prompt, user_id=None):
    """Фоновая задача для свободного чата с ИИ"""
    try:
        system_msg = "You are a helpful assistant."
        full_prompt = f"HISTORY:\n{history_context}\nREQUEST:\n{user_prompt}"
        
        success, resp = ask_llm(sel_prov, sel_model, system_msg, full_prompt, user_id=user_id)
        
        if success:
            return {"status": True, "msg": resp}
        else:
            return {"status": False, "msg": f"Ошибка AI: {resp}"}
            
    except Exception as e:
        return {"status": False, "msg": str(e)}